global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "llm-training"
    static_configs:
      - targets: ["host.docker.internal:8000"]  # if Prometheus runs in Docker on Mac
        labels:
          env: "local"
